version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: "daily"
  milestone: 6
  ignore:
  - dependency-name: ch.qos.logback:logback-classic
    update-types:
    - version-update:semver-minor
  - dependency-name: org.jline:jline
    update-types:
    - version-update:semver-major
    - version-update:semver-minor

- package-ecosystem: "github-actions"
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: "daily"
  milestone: 6
